application: debiancdn
version: 1
runtime: python
api_version: 1

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /managesurrogate
  script: managesurrogate.py

- url: /checksurrogate
  script: checksurrogate.py
  login: admin

- url: /resetcheckpref
  script: resetcheckpref.py
  login: admin  

- url: /deletesurrogate
  script: managesurrogate.py
  login: admin

- url: /removesurrogate
  script: managesurrogate.py
  login: admin

- url: /addsurrogate
  script: managesurrogate.py
  login: admin

- url: /.*surrogate
  script: managesurrogate.py
  login: admin

- url: /lists/.*
  script: lists.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /json/.*
  script: json.py

- url: .*
  script: main.py
